#!/bin/bash

# Script to display listening ports with PID and program name

echo "Listening ports with PID and program name:"
echo "-------------------------------------------"

# Use 'ss' command to list listening sockets
# '-l' : Show only listening sockets
# '-p' : Show the process using the socket
# '-t' : Show TCP sockets
# '-u' : Show UDP sockets
# '-n' : Do not resolve names (shows ports and addresses as numbers)

ss -tulnp | awk '
NR == 1 { print $0 } # Print the header row
NR > 1 { print $0 }  # Print the rest of the rows
'
